.TH "bup\-init" "1" "2014\-06\-30" "Bup 0.26\-rc1\-28\-g7918009" ""
.SH NAME
.PP
bup\-init \- initialize a bup repository
.SH SYNOPSIS
.PP
[BUP_DIR=\f[I]localpath\f[]] bup init [\-r \f[I]host\f[]:\f[I]path\f[]]
.SH DESCRIPTION
.PP
\f[C]bup\ init\f[] initializes your local bup repository.
By default, BUP_DIR is \f[C]~/.bup\f[].
.SH OPTIONS
.TP
.B \-r, \-\-remote=\f[I]host\f[]:\f[I]path\f[]
Initialize not only the local repository, but also the remote repository
given by the \f[I]host\f[] and \f[I]path\f[].
This is not necessary if you intend to back up to the default location
on the server (ie.
a blank \f[I]path\f[]).
The connection to the remote server is made with SSH.
If you\[aq]d like to specify which port, user or private key to use for
the SSH connection, we recommend you use the \f[C]~/.ssh/config\f[]
file.
.RS
.RE
.SH EXAMPLES
.IP
.nf
\f[C]
bup\ init
\f[]
.fi
.SH SEE ALSO
.PP
\f[C]bup\-fsck\f[](1), \f[C]ssh_config\f[](5)
.SH BUP
.PP
Part of the \f[C]bup\f[](1) suite.
.SH AUTHORS
Avery Pennarun <apenwarr@gmail.com>.
