
task:
  name: debian (py2)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python2
    dev/system-info
    eatmydata make -j6 PYTHON=python2 check

task:
  name: debian (long py2)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python2
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j6 -C '$(pwd)' PYTHON=python2 long-check"

task:
  name: debian (root py2)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python2
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j6 -C '$(pwd)' PYTHON=python2 check"

task:
  name: debian (py3)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    dev/system-info
    eatmydata make -j6 PYTHON=python3 check

task:
  name: debian (long py3)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j6 -C '$(pwd)' PYTHON=python3 long-check"

task:
  name: debian (root py3)
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j6 -C '$(pwd)' PYTHON=python3 check"

task:
  name: freebsd (py3)
  freebsd_instance:
    image: freebsd-12-1-release-amd64
    cpu: 4
    memory: 4
  script: |
    set -xe
    dev/prep-for-freebsd-build python3
    dev/system-info
    gmake -j6 PYTHON=python3.7 check

task:
  name: macos (py2)
  allow_failures: true
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
  script: |
    set -xe
    dev/prep-for-macos-build python2
    eval "$(pyenv init -)"
    export PKG_CONFIG_PATH=/usr/local/opt/readline/lib/pkgconfig
    dev/system-info
    pyenv exec make -j4 PYTHON=python check

task:
  name: macos (py3)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  script: |
    set -xe
    dev/prep-for-macos-build python3
    export PKG_CONFIG_PATH=/usr/local/opt/readline/lib/pkgconfig
    export PYTHON=python3
    dev/system-info
    make -j4 PYTHON=python3 check
