
task:
  name: debian check/lint root
  container:
    image: debian:bullseye
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    export LANG=C.UTF-8
    dev/system-info
    BUP_PYTHON_CONFIG=python3-config ./configure --with-pylint=yes
    make -j6 check

task:
  name: debian long-check
  container:
    image: debian:bullseye
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    export LANG=C.UTF-8
    DEBIAN_FRONTEND=noninteractive apt-get -y install bup
    export BUP_TEST_OTHER_BUP="$(command -v bup)"
    "$BUP_TEST_OTHER_BUP" version
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    printf "make -j6 -C %q BUP_PYTHON_CONFIG=python3-config long-check" \
      "$(pwd)" | su -l -w BUP_TEST_OTHER_BUP bup

task:
  name: debian check
  container:
    image: debian:buster
    cpu: 4
    memory: 2
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    export LANG=C.UTF-8
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    printf "make -j6 -C %q BUP_PYTHON_CONFIG=python3-config check" \
      "$(pwd)" | su -l bup

task:
  name: freebsd check
  freebsd_instance:
    image: freebsd-13-2-release-amd64
    cpu: 4
    memory: 4
  script: |
    set -xe
    dev/prep-for-freebsd-build python3
    dev/system-info
    gmake -j6 check

task:
  name: macos check
  macos_instance:
    # https://cirrus-ci.org/guide/macOS/
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  script: |
    set -xe
    dev/prep-for-macos-build python3
    brew install bup
    export BUP_TEST_OTHER_BUP="$(command -v bup)"
    "$BUP_TEST_OTHER_BUP" version
    export PKG_CONFIG_PATH=/usr/local/opt/readline/lib/pkgconfig
    dev/system-info
    gmake -j6 BUP_PYTHON_CONFIG=python3-config LDFLAGS=-L/usr/local/lib check
