
task:
  name: debian
  container:
    image: debian:buster
    cpu: 2
    memory: 8
  script: |
    set -xe
    dev/prep-for-debianish-build
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j3 -C '$(pwd)' check"

task:
  name: debian-xattr
  container:
    image: debian:buster
    cpu: 2
    memory: 8
  script: |
    set -xe
    dev/prep-for-debianish-build python2 xattr
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    su -l bup -c "eatmydata make -j3 -C '$(pwd)' check"

task:
  name: freebsd
  freebsd_instance:
    image: freebsd-11-2-release-amd64
    cpu: 2
    memory: 8
  script: |
    set -xe
    dev/prep-for-freebsd-build
    dev/system-info
    gmake -j3 check
    # It looks like su might not work here...
    #pw useradd -n bup -s /bin/sh -m -w no
    #chown -R bup .
    #su -l bup -c "gmake -j3 -C '$PWD' check"

task:
  name: macos
  osx_instance:
    image: mojave-xcode-10.2
  script: |
    set -xe
    dev/prep-for-macos-build
    dev/system-info
    make -j3 check

task:
  name: debian (python 3 - under construction)
  container:
    image: debian:buster
    cpu: 2
    memory: 8
  script: |
    set -xe
    dev/prep-for-debianish-build python3
    dev/system-info
    adduser --disabled-password --gecos '' bup
    chown -R bup:bup .
    testcmd='BUP_ALLOW_UNEXPECTED_PYTHON_VERSION=true PYTHON=python3'
    testcmd="$testcmd eatmydata make -j3 -C '$(pwd)' check"
    su -l bup -c "$testcmd"
