.TH bup-import-rsnapshot 1 "2011-03-01" "Bup 0\.24-83-gdfa9d85"
.SH NAME
.PP
bup-import-rsnapshot - import a rsnapshot archive
.SH SYNOPSIS
bup import-rsnapshot [-n]
<path to snapshot_root> 
[
<backuptarget>
.PP
]
.SH SYNOPSIS
.PP
\f[B]bup\ import-rsnapshot\f[] imports an rsnapshot archive\. The
timestamps for the backups are preserved and the path to the
rsnapshot archive is stripped from the paths\.
.PP
\f[B]bup\ import-rsnapshot\f[] either imports the whole archive or
imports all backups only for a given backuptarget\.
.SH OPTIONS
.TP
.B -n,--dry-run
don\[aq]t do anything just print out what would be done
.RS
.RE
.SH EXAMPLES
.PP
\f[CR]
      $\ bup\ import-rsnapshot\ /\.snapshots
      
      $\ bup\ import-rsnapshot\ /\.snapshots\ host1
\f[]
.SH BUP
.PP
Part of the \f[B]bup\f[](1) suite\.
.SH AUTHOR
Zoran Zaric <zz@zoranzaric.de>
