.TH bup-help 1 "2011-02-01" "Bup 0\.22"
.SH NAME
.PP
bup-help - open the documentation for a given bup command
.SH SYNOPSIS
.PP
bup help <command>
.SH DESCRIPTION
.PP
\f[B]bup\ help\ <command>\f[] opens the documentation for the given
command\. This is currently equivalent to typing
\f[B]man\ bup-<command>\f[]\.
.SH EXAMPLE
.PP
\f[CR]
      $\ bup\ help\ help
      (Imagine\ that\ this\ man\ page\ was\ pasted\ below,
      \ recursively\.\ \ Since\ that\ would\ cause\ an\ endless\ loop
      \ we\ include\ this\ silly\ remark\ instead\.\ \ Chicken\.)
\f[]
.SH BUP
.PP
Part of the \f[B]bup\f[](1) suite\.
.SH AUTHOR
Avery Pennarun <apenwarr@gmail.com>
