.TH "bup\-import\-rsnapshot" "1" "2014\-06\-30" "Bup 0.26\-rc1\-28\-g7918009" ""
.SH NAME
.PP
bup\-import\-rsnapshot \- import a rsnapshot archive
.SH SYNOPSIS
.PP
bup import\-rsnapshot [\-n] <path to snapshot_root> [<backuptarget>]
.SH SYNOPSIS
.PP
\f[C]bup\ import\-rsnapshot\f[] imports an rsnapshot archive.
The timestamps for the backups are preserved and the path to the
rsnapshot archive is stripped from the paths.
.PP
\f[C]bup\ import\-rsnapshot\f[] either imports the whole archive or
imports all backups only for a given backuptarget.
.SH OPTIONS
.TP
.B \-n, \-\-dry\-run
don\[aq]t do anything just print out what would be done
.RS
.RE
.SH EXAMPLES
.IP
.nf
\f[C]
$\ bup\ import\-rsnapshot\ /.snapshots

$\ bup\ import\-rsnapshot\ /.snapshots\ host1
\f[]
.fi
.SH BUP
.PP
Part of the \f[C]bup\f[](1) suite.
.SH AUTHORS
Zoran Zaric <zz@zoranzaric.de>.
