.TH "bup\-ftp" "1" "2014\-06\-30" "Bup 0.26\-rc1\-28\-g7918009" ""
.SH NAME
.PP
bup\-ftp \- ftp\-like client for navigating bup repositories
.SH SYNOPSIS
.PP
bup ftp
.SH DESCRIPTION
.PP
\f[C]bup\ ftp\f[] is a command\-line tool for navigating bup
repositories.
It has commands similar to the Unix \f[C]ftp\f[](1) command.
The file hierarchy is the same as that shown by \f[C]bup\-fuse\f[](1)
and \f[C]bup\-ls\f[](1).
.PP
Note: if your system has the python\-readline library installed, you can
use the <tab> key to complete filenames while navigating your backup
data.
This will save you a lot of typing.
.SH COMMANDS
.PP
The following commands are available inside \f[C]bup\ ftp\f[]:
.TP
.B ls [\-s] [\-a] [\f[I]path\f[]]
print the contents of a directory.
If no path argument is given, the current directory\[aq]s contents are
listed.
If \-a is given, also include hidden files (files which start with a
\f[C]\&.\f[] character).
If \-s is given, each file is displayed with its hash from the bup
archive to its left.
.RS
.RE
.TP
.B cd \f[I]dirname\f[]
change to a different working directory
.RS
.RE
.TP
.B pwd
print the path of the current working directory
.RS
.RE
.TP
.B cat \f[I]filenames...\f[]
print the contents of one or more files to stdout
.RS
.RE
.TP
.B get \f[I]filename\f[] \f[I]localname\f[]
download the contents of \f[I]filename\f[] and save it to disk as
\f[I]localname\f[].
If \f[I]localname\f[] is omitted, uses \f[I]filename\f[] as the local
name.
.RS
.RE
.TP
.B mget \f[I]filenames...\f[]
download the contents of the given \f[I]filenames\f[] and stores them to
disk under the same names.
The filenames may contain Unix filename globs (\f[C]*\f[], \f[C]?\f[],
etc.)
.RS
.RE
.TP
.B help
print a list of available commands
.RS
.RE
.TP
.B quit
exit the \f[C]bup\ ftp\f[] client
.RS
.RE
.SH EXAMPLES
.IP
.nf
\f[C]
$\ bup\ ftp
bup>\ ls
mybackup/\ \ \ \ yourbackup/

bup>\ cd\ mybackup/
bup>\ ls
2010\-02\-05\-185507\@\ \ \ 2010\-02\-05\-185508\@\ \ \ \ latest\@

bup>\ cd\ latest/
bup>\ ls
\ \ (...etc...)

bup>\ get\ myfile
Saving\ \[aq]myfile\[aq]
bup>\ quit
\f[]
.fi
.SH SEE ALSO
.PP
\f[C]bup\-fuse\f[](1), \f[C]bup\-ls\f[](1), \f[C]bup\-save\f[](1),
\f[C]bup\-restore\f[](1)
.SH BUP
.PP
Part of the \f[C]bup\f[](1) suite.
.SH AUTHORS
Avery Pennarun <apenwarr@gmail.com>.
