.TH "bup\-ls" "1" "2014\-06\-30" "Bup 0.26\-rc1\-28\-g7918009" ""
.SH NAME
.PP
bup\-ls \- list the contents of a bup repository
.SH SYNOPSIS
.PP
bup ls [OPTION...] <paths...>
.SH DESCRIPTION
.PP
\f[C]bup\ ls\f[] lists files and directories in your bup repository
using the same directory hierarchy as they would have with
\f[C]bup\-fuse\f[](1).
.PP
The top level directory contains the branch (corresponding to the
\f[C]\-n\f[] option in \f[C]bup\ save\f[]), the next level is the date
of the backup, and subsequent levels correspond to files in the backup.
.PP
When \f[C]bup\ ls\f[] is asked to output on a tty, and \f[C]\-l\f[] is
not specified, it formats the output in columns so it can list as much
as possible in as few lines as possible.
However, when \f[C]\-l\f[] is specified or bup is asked to output to
something other than a tty (say you pipe the output to another command,
or you redirect it to a file), it will print one file name per line.
This makes the listing easier to parse with external tools.
.PP
Note that \f[C]bup\ ls\f[] doesn\[aq]t show hidden files by default and
one needs to use the \f[C]\-a\f[] option to show them.
Files are hidden when their name begins with a dot.
For example, on the topmost level, the special directories named
\f[C]\&.commit\f[] and \f[C]\&.tag\f[] are hidden directories.
.PP
Once you have identified the file you want using \f[C]bup\ ls\f[], you
can view its contents using \f[C]bup\ join\f[] or \f[C]git\ show\f[].
.SH OPTIONS
.TP
.B \-s, \-\-hash
show hash for each file/directory.
.RS
.RE
.TP
.B \-a, \-\-all
show hidden files.
.RS
.RE
.TP
.B \-A, \-\-almost\-all
show hidden files, except "." and "..".
.RS
.RE
.TP
.B \-d, \-\-directory
show information about directories themselves, rather than their
contents, and don\[aq]t follow symlinks.
.RS
.RE
.TP
.B \-l
provide a detailed, long listing for each item.
.RS
.RE
.TP
.B \-F, \-\-classify
append type indicator: dir/, symlink\@, fifo|, socket=, and executable*.
.RS
.RE
.TP
.B \-\-file\-type
append type indicator: dir/, symlink\@, fifo|, socket=.
.RS
.RE
.TP
.B \-\-human\-readable
print human readable file sizes (i.e.
3.9K, 4.7M).
.RS
.RE
.TP
.B \-\-numeric\-ids
display numeric IDs (user, group, etc.) rather than names.
.RS
.RE
.SH EXAMPLES
.IP
.nf
\f[C]
bup\ ls\ /myserver/latest/etc/profile

bup\ ls\ \-a\ /
\f[]
.fi
.SH SEE ALSO
.PP
\f[C]bup\-join\f[](1), \f[C]bup\-fuse\f[](1), \f[C]bup\-ftp\f[](1),
\f[C]bup\-save\f[](1), \f[C]git\-show\f[](1)
.SH BUP
.PP
Part of the \f[C]bup\f[](1) suite.
.SH AUTHORS
Avery Pennarun <apenwarr@gmail.com>.
