.TH bup-mux 1 "2011\[en]06\[en]08" "Bup 0.25-rc1"
.SH NAME
.PP
bup-mux - multiplexes data and error streams over a connection
.SH SYNOPSIS
.PP
bup mux <command> [options\&...]
.SH DESCRIPTION
.PP
\f[B]bup\ mux\f[] is used in the bup client-server protocol to send
both data and debugging/error output over the single connection
stream.
.PP
\f[B]bup\ mux\ server\f[] might be used in an inetd server setup.
.SH OPTIONS
.TP
.B command
the subcommand to run
.RS
.RE
.TP
.B options
options for command
.RS
.RE
.SH BUP
.PP
Part of the \f[B]bup\f[](1) suite.
.SH AUTHORS
Brandon Low <lostlogic@lostlogicx.com>.

