.TH bup\-fuse 1 "2013\-12\-09" "Bup 0.25"
.SH NAME
.PP
bup\-fuse \- mount a bup repository as a filesystem
.SH SYNOPSIS
.PP
bup fuse [\-d][\-f] [\-o] <mountpoint>
.SH DESCRIPTION
.PP
\f[C]bup\ fuse\f[] opens a bup repository and exports it as a
\f[C]fuse\f[](7) userspace filesystem.
.PP
This feature is only available on systems (such as Linux) which support
FUSE.
.PP
\f[B]WARNING\f[]: bup fuse is still experimental and does not enforce
any file permissions! All files will be readable by all users.
.PP
When you\[aq]re done accessing the mounted fuse filesystem, you should
unmount it with \f[C]umount\f[](8).
.SH OPTIONS
.TP
.B \-d, \-\-debug
run in the foreground and print FUSE debug information for each request.
.RS
.RE
.TP
.B \-f, \-\-foreground
run in the foreground and exit only when the filesystem is unmounted.
.RS
.RE
.TP
.B \-o, \-\-allow\-other
permit other users to access the filesystem.
Necessary for exporting the filesystem via Samba, for example.
.RS
.RE
.SH EXAMPLE
.IP
.nf
\f[C]
rm\ \-rf\ /tmp/buptest
mkdir\ /tmp/buptest
sudo\ bup\ fuse\ \-d\ /tmp/buptest
ls\ /tmp/buptest/*/latest
\&...
umount\ /tmp/buptest
\f[]
.fi
.SH SEE ALSO
.PP
\f[C]fuse\f[](7), \f[C]fusermount\f[](1), \f[C]bup\-ls\f[](1),
\f[C]bup\-ftp\f[](1), \f[C]bup\-restore\f[](1), \f[C]bup\-web\f[](1)
.SH BUP
.PP
Part of the \f[C]bup\f[](1) suite.
.SH AUTHORS
Avery Pennarun <apenwarr@gmail.com>.
