#!/bin/sh

set -e

script_home="$(cd "$(dirname "$0")" && pwd -P)"
python="$script_home/../config/bin/python"
libdir="$script_home/../lib"

export PYTHONPATH="$libdir${PYTHONPATH:+:$PYTHONPATH}"
exec "$python" "$@"
