#!/bin/sh
"""": # -*-python-*-
bup_exec="$(dirname "$0")/bup-exec" || exit $?
exec "$bup_exec" "$0" ${1+"$@"}
"""


from os.path import abspath, dirname
from sys import stdout
import os, sys

from bup import compat

for arg in compat.get_argvb():
    os.write(stdout.fileno(), arg)
    os.write(stdout.fileno(), b'\0\n')
    stdout.flush()
