#!/bin/sh
"""": # -*-python-*-
bup_exec="$(dirname "$0")/bup-exec" || exit $?
exec "$bup_exec" "$0" ${1+"$@"}
"""

import socket, sys

from bup.compat import get_argvb

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0)
s.bind(get_argvb()[1])
