#!/bin/sh
"""": # -*-python-*-
bup_python="$(dirname "$0")/../config/bin/python" || exit $?
exec "$bup_python" "$0" ${1+"$@"}
"""
# end of bup preamble

from __future__ import absolute_import

import socket, sys

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0)
s.bind(sys.argv[1])
