#!/bin/sh
"""": # -*-python-*-
# https://sourceware.org/bugzilla/show_bug.cgi?id=26034
export "BUP_ARGV_0"="$0"
arg_i=1
for arg in "$@"; do
    export "BUP_ARGV_${arg_i}"="$arg"
    shift
    arg_i=$((arg_i + 1))
done
bup_python="$(dirname "$0")/bup-python" || exit $?
exec "$bup_python" "$0"
"""
# end of bup preamble

from __future__ import absolute_import
import os.path, sys

sys.path[:0] = [os.path.dirname(os.path.realpath(__file__)) + '/../../lib']

from bup.compat import argv_bytes
from bup.helpers import handle_ctrl_c, saved_errors
from bup.io import byte_stream
from bup import compat, metadata, options
import bup.xstat as xstat


optspec = """
ns-timestamp-resolutions TEST_FILE_NAME
--
"""

handle_ctrl_c()

o = options.Options(optspec)
opt, flags, extra = o.parse(compat.argv[1:])

sys.stdout.flush()
out = byte_stream(sys.stdout)

if len(extra) != 1:
    o.fatal('must specify a test file name')

target = argv_bytes(extra[0])

open(target, 'w').close()
xstat.utime(target, (123456789, 123456789))
meta = metadata.from_path(target)

def ns_resolution(x):
    n = 1;
    while n < 10**9 and x % 10 == 0:
        x /= 10
        n *= 10
    return n

out.write(b'%d %d\n' % (ns_resolution(meta.atime),
                        ns_resolution(meta.mtime)))

if saved_errors:
    log('warning: %d errors encountered\n' % len(saved_errors))
    sys.exit(1)
