#!/bin/sh

set -exu

usage()
{
    echo "Usage: prep-for-freebsd-build [python2|python3]"
}

common_pkgs='gmake git bash rsync curl par2cmdline readline duplicity'
common_pkgs="$common_pkgs rsnapshot"

pyver="${1:-python2}"

# Install build deps
export ASSUME_ALWAYS_YES=yes
pkg update

# https://reviews.freebsd.org/D24816
pkg install rdiff-backup || true

case "$pyver" in
    python2)
        pkg install $common_pkgs python2 py27-tornado pytest pytest-xdist
        ;;
    python3)
        pkg install $common_pkgs python3 py37-tornado pytest3 pytest3-xdist
        ;;
    *)
        usage 1>&2
        exit 2
        ;;
esac
