#!/bin/sh

set -exu

usage()
{
    echo "Usage: prep-for-freebsd-build"
}

# Install build deps
export ASSUME_ALWAYS_YES=yes
pkg update

# https://reviews.freebsd.org/D24816
pkg install rdiff-backup || true

pkgs='gmake git bash rsync curl par2cmdline readline duplicity'
pkgs="$pkgs rsnapshot hs-pandoc graphviz"
pkgs="$pkgs python311 py311-tornado py311-pytest py311-pytest-xdist"
pkg install $pkgs
