#!/bin/sh

set -exu

usage()
{
    echo "Usage: prep-for-freebsd-build [python2|python3]"
}

pyver="${1:-python2}"

# Install build deps
export ASSUME_ALWAYS_YES=yes
pkg update

# https://reviews.freebsd.org/D24816
pkg install rdiff-backup || true

pkgs='gmake git bash rsync curl par2cmdline readline duplicity'
pkgs="$pkgs rsnapshot"

case "$pyver" in
    python2)
        pkgs="$pkgs python2 py27-tornado pytest pytest-xdist"
        ;;
    python3)
        pkgs="$pkgs python37 py37-tornado py37-pytest py37-pytest-xdist"
        ;;
    *)
        usage 1>&2
        exit 2
        ;;
esac

pkg install $pkgs
