#!/usr/bin/env bash

set -exu

usage()
{
    echo "Usage: prep-for-macos-build [python2|python3]"
}

pyver="${1:-python2}"

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew update
brew install par2 readline rsync pkg-config md5sha1sum

# This avoid's macos interference, i.e. without this it looks like we
# won't actually be able to use the readline we just installed above.
brew link --force readline
# "brew unlink readline" will undo this hack

case "$pyver" in
    python2)
        easy_install-2.7 --user pip
        /Users/anka/Library/Python/2.7/bin/pip install --user pytest pytest-xdist
        ;;
    python3)
        brew install python
        easy_install --user pip
        pip3 install --user pytest pytest-xdist
        ;;
    *)
        usage 1>&2
        exit 2
        ;;
esac
