#!/bin/sh
"""": # -*-python-*-
python="$(dirname "$0")/python" || exit $?
exec "$python" "$0" ${1+"$@"}
"""

import os, sys

if sys.platform.startswith('cygwin'):
    # see helpers.getgroups()
    egid = os.getegid()
    groups = os.getgroups()
    if egid not in groups:
        groups.append(egid)
    if 544 in groups or 0 in groups:
        print('root')
    else:
        print('none')
else:
    if os.environ.get('FAKEROOTKEY'):
        print('fake')
    else:
        if os.geteuid() == 0:
            print('root')
        else:
            print('none')
