#!/bin/sh
"""": # -*-python-*-
python="$(dirname "$0")/python" || exit $?
exec "$python" "$0" ${1+"$@"}
"""

from __future__ import absolute_import, print_function

import grp
import pwd
import sys

def usage():
    print("Usage: unknown-owner (--user | --group)", file=sys.stderr)

if len(sys.argv) != 2:
    usage()
    sys.exit(1)

if sys.argv[1] == '--user':
    max_name_len = max([len(x.pw_name) for x in pwd.getpwall()])
elif sys.argv[1] == '--group':
    max_name_len = max([len(x.gr_name) for x in grp.getgrall()])
else:
    usage()
    sys.exit(1)

print('x' * (max_name_len + 1))
