#!/usr/bin/env bash

set -eu

usage() { echo "Usage: validate-make MAKE"; }
misuse() { usage 1>&2; exit 2; }

test $# -eq 1 || misuse
make="$1"

msg="$("$make" --version)"
gnu="$(echo "$msg" | grep 'GNU Make')"

if test $? -ne 0; then
    echo '$make does not appear to be GNU Make' 1>&2
    exit 2
fi

# Expecting something like "GNU Make 4.3"
ver=$(echo "$gnu" | awk '{print $3}')

if test -z "$ver"; then
    printf 'Unable to find make version in %q --version output\n' "$make" 1>&2
    exit 2
fi    

# Technically we need 4.1.90 for .SHELLSTATUS, but everything relevant
# seems to have at least 4.2 (mostly 4.4 and higher) anyway, so let's
# just require 4.2+ to simplify.

if ! expr "$ver" '>=' '4.2' > /dev/null; then
    printf '%q version ("%q") does not appear to be 4.2 or newer\n' "$make" "$gnu" 1>&2
fi
