#!/usr/bin/env bash

set -ueo pipefail

usage() { echo 'Usage: with-tty command [arg ...]'; }
misuse() { usage 1>&2; exit 2; }

if script -qec true /dev/null; then
    # linux flavor
    script -qec "$(printf ' %q' "$@")" /dev/null
else
    # bsd flavor
    script -qe /dev/null "$@"
fi
