#!/usr/bin/env bash
. wvtest.sh || exit $?
. wvtest-bup.sh || exit $?

set -o pipefail

if test -z "$BUP_TEST_OTHER_BUP"; then
    WVSKIP 'no BUP_TEST_OTHER_BUP'
    exit 0
fi

export BUP_TEST_REMOTE_REPO=t # as per test-ls-remote
export BUP_TEST_SSH_BUP_PATH="$BUP_TEST_OTHER_BUP"

test/ext/test-ls
