#!/usr/bin/env bash
. ./wvtest-bup.sh || exit $?
. test/lib/btl.sh || exit $?

set -o pipefail

top="$(WVPASS pwd)" || exit $?
tmpdir="$(WVPASS wvmktempdir)" || exit $?

export BUP_DIR="$tmpdir/bup"
export GIT_DIR="$tmpdir/bup"

bup() { "$top/bup" "$@"; }

WVPASS cd "$tmpdir"
WVPASS bup init

WVPASS mkdir -p src/a
WVPASS echo 1 > src/a/1
WVPASS echo 2 > src/a/2
WVPASS echo 3 > src/a/3
WVPASS bup index src
WVPASS bup save --strip -n src src

WVPASS bup validate-object-links | tee validate-out
WVPASS test -z "$(<validate-out)"

bupm_oid="$(WVPIPE git ls-tree src:a | WVPASS head -1 | WVPASS btl-ent-oid)" \
    || exit $?
echo "$bupm_oid" | WVPASS "$top/dev/perforate-repo" --drop-oids "$BUP_DIR"

set -x
bup validate-object-links > validate-out
rc=$?
set +x
cat validate-out
WVPASSEQ 1 "$rc"

src_a_oid="$(git rev-parse src:a)"
WVPASS grep -E "^no $bupm_oid for $src_a_oid" validate-out

WVPASS cd "$top"
WVPASS rm -rf "$tmpdir"
