#!/usr/bin/env bash
. ./wvtest-bup.sh

set -o pipefail

top="$(WVPASS pwd)" || exit $?
tmpdir="$(WVPASS wvmktempdir)" || exit $?
export BUP_DIR="$tmpdir/bup"
export GIT_DIR="$tmpdir/bup"

bup() { "$top/bup" "$@"; }

# FIXME: send help to stdout if requested (exit 0), stderr on error
# (exit nonzero)

bup -?
rc=$?
WVPASSEQ 99 "$rc"

bup --help
rc=$?
WVPASSEQ 99 "$rc"

if ! test -e Documentation/bup-save.1; then
    WVPASS rm -rf "$tmpdir"
    exit 0
fi

mkdir -p "$tmpdir/man"
(cd "$tmpdir/man" && ln -s "$top/Documentation" man1)
export MANPATH="$tmpdir/man"

PAGER=cat WVPASS bup help save
PAGER=cat WVPASS bup save --help
WVPASSEQ 1 $(bup help save | grep -cE 'bup.save . create a new bup backup set')
WVPASSEQ 1 $(bup save --help | grep -cE 'bup.save . create a new bup backup set')

WVPASS cd "$top"
WVPASS rm -rf "$tmpdir"
