#!/usr/bin/env bash

set -e -o pipefail

top=$(pwd)

usage()
{
    echo 'Usage: t/configure-sampledata [--setup | --clean]'
}

if test "$#" -ne 1; then
    usage 1>&2; exit 1
fi

case "$1" in
    '--setup')
        (
            cd t/sampledata
            ln -sf a b
            ln -sf b c
            ln -sf /etc .
        )
        ;;
    '--clean')
        (
            cd t/sampledata
            # test -e is false for dangling symlinks.
            if test -h b -o -e b; then rm b; fi
            if test -h c -o -e c; then rm c; fi
            if test -h etc -o -e etc; then rm etc; fi
        )
        ;;
    *)
        usage 1>&2; exit 1
        ;;
esac
