#!/bin/sh
"""": # -*-python-*-
bup_python="$(dirname "$0")/../cmd/bup-python" || exit $?
exec "$bup_python" "$0" ${1+"$@"}
"""
# end of bup preamble

from sys import stderr
import sys

if sys.platform.startswith('cygwin'):
    groups = os.getgroups()
    if 544 in groups or 0 in groups:
        print 'root'
    else:
        print 'none'
else:
    import os
    if os.environ.get('FAKEROOTKEY'):
        print 'fake'
    else:
        if os.geteuid() == 0:
            print 'root'
        else:
            print 'none'
