#!/usr/bin/env python

import grp
import pwd
import sys

def usage():
    print >> sys.stderr, "Usage: some-owners (--user | --group)"

if len(sys.argv) != 2:
    usage()
    sys.exit(1)

if sys.argv[1] == '--user':
    non_root_users = [x.pw_name for x in pwd.getpwall() if x.pw_name != 'root']
    print non_root_users[0]
elif sys.argv[1] == '--group':
    non_root_groups = [x.gr_name for x in grp.getgrall() if x.gr_name != 'root']
    print non_root_groups[0]
else:
    usage()
    sys.exit(1)
